In [0]:
from keras import models
import os
import pylab
import numpy as np
from skimage import io
import csv
from google.colab import drive

In [40]:
drive.mount('/content/drive')

parent_dir = '/content/drive/My Drive/Colab Notebooks/Testing/Specs/Ml'
model_dir = 'good models/Custms1.h5'
img_dir = ['test/direct_speech', 'test/bg', 'test/bab']
results_dir = ['results/cust_cat3_test_ds.csv', 'results/cust_cat3_test_env.csv', 'results/cust_cat3_test_bab.csv']
tags = ['-direct.jpg', '-bg.jpg', '_test.jpg']

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
model_path = os.path.join(parent_dir, model_dir)


In [42]:
model = models.load_model(model_path)
print(model_path)

/content/drive/My Drive/Colab Notebooks/Testing/Specs/Ml/good models/Custms1.h5


In [43]:
for j in range(0, 3):
  results_path = os.path.join(parent_dir, results_dir[j])
  image_path = os.path.join(parent_dir, img_dir[j])
  for i in range(3000, 12000):
      filename = str(i) + tags[j]
      filepath = os.path.join(image_path, filename)
      if os.path.exists(filepath):
        all_images = []
        img = io.imread(filepath)
        img = img.reshape([224, 224, 3])
        img = img/225
        all_images.append(img)
        x = np.array(all_images)
        answer = model.predict(x, batch_size=None, verbose=1, steps=None)
        print(answer)


        row = [filename, answer]

        with open(results_path, 'a') as csvFile:
            writer = csv.writer(csvFile)
            writer.writerow(row)

        csvFile.close()
        print('Written')
      else: 
        print('FileNotFound')

1/1 [==============================] - 4s 4s/step
[[4.4608719e-26 1.0000000e+00 4.9861382e-17]]
Written
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
1/1 [==============================] - 0s 6ms/step
[[2.1160220e-16 1.0000000e+00 1.9376886e-10]]
Written
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
1/1 [==============================] - 0s 5ms/step
[[1.4360346e-14 1.0000000e+00 1.6639973e-10]]
Written
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
1/1 [==============================] - 0s 5ms/step
[[4.0040473e-16 1.0000000e+00 6.0937810e-10]]
Written
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
FileNotFound
1/1 [==============================] - 0s 5ms/step
[[2.1901500e-22 1.0000000e+00 5.4732083e-12]]
Written
FileNotF